---
name: "issue-metrics"
author: "github"
description: "A GitHub Action to report out issue metrics"
runs:
  using: "composite"
  steps:
    - name: metrics
      shell: bash
      run: |
        uv run \
          --with-requirements requirements.txt \
          --python 3.13 \
          --no-project \
          python -u ./${{ github.action_path }}/issue_metrics.py


branding:
  icon: "check-square"
  color: "white"
